DROP TABLE IF EXISTS user_cinema;

CREATE TABLE IF NOT EXISTS user_cinema (
    ID_User INTEGER AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Age INT NOT NULL,
    Username VARCHAR(100) NOT NULL,
    Password VARCHAR(250) NOT NULL,
    Account VARCHAR(20) NOT NULL
);

